/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/w3c/css/': RouteRecordInfo<
      '/w3c/css/',
      '/w3c/css',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/w3c/css/flex/': RouteRecordInfo<
      '/w3c/css/flex/',
      '/w3c/css/flex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/w3c/js/proxy': RouteRecordInfo<
      '/w3c/js/proxy',
      '/w3c/js/proxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/w3c/wasm/': RouteRecordInfo<
      '/w3c/wasm/',
      '/w3c/wasm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
    }
    'src/pages/w3c/css/index.vue': {
      routes:
        | '/w3c/css/'
      views:
        | never
    }
    'src/pages/w3c/css/flex/index.vue': {
      routes:
        | '/w3c/css/flex/'
      views:
        | never
    }
    'src/pages/w3c/js/proxy.vue': {
      routes:
        | '/w3c/js/proxy'
      views:
        | never
    }
    'src/pages/w3c/wasm/index.vue': {
      routes:
        | '/w3c/wasm/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
